pull_request_rules:
  - name: Automatic merge for main when CI passes and 1 review
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=build 
      - base=main
    actions:
      merge:
        method: merge
